import { colors } from './colors';

export const chart = {
  lineStroke: 2,
  markerRadius: 4,
  highlightRadius: 6,
  ringWidth: 2,
  barMaxWidth: 24,
  barMinWidth: 6,
  barRadius: 4,
  barGap: 2,
  gridStroke: 1,
  yAxisWidth: 38,
  xAxisHeight: 22,
  topPadding: 22,
  rightPadding: 10,
  yTicks: 3,
  maxMarkers: 12,
  areaOpacity: 0.1,
  targetOpacity: 0.55,
  hbarHeight: 12,
  hbarLabelWidth: 92,
  hbarValueWidth: 40,
  colors: {
    line: colors.forest,
    area: colors.forest,
    marker: colors.forest,
    highlight: colors.lime,
    ring: colors.paper,
    grid: colors.border,
    axisText: colors.muted,
    barMuted: colors.mintSoft,
    barStrong: colors.forest,
    target: colors.mint,
    crosshair: colors.mutedLight,
  },
} as const;
