export const routes = {
  home: '/',
  plan: '/plan',
  progress: '/progress',
  more: '/more',
  workout: '/workout',
  workoutExercise: (index: number) => `/workout/${index}` as const,
  workoutSummary: '/workout/summary',
  exercise: (id: string) => `/exercise/${id}` as const,
  exercisePicker: '/exercise/picker',
  session: (id: string) => `/session/${id}` as const,
  programs: '/programs',
  program: (pid: string) => `/programs/${pid}` as const,
  programWorkout: (pid: string, wid: string) => `/programs/${pid}/${wid}` as const,
  body: '/body',
  cardio: '/cardio',
  plates: '/plates',
  settings: '/settings',
  backup: '/backup',
} as const;
