import type { RestSoundMode } from '@/types/backup';

export const REST_SOUND_MODES: RestSoundMode[] = ['app', 'system', 'off'];

/** Generated by scripts/generate-sounds.ts. Each tone is [frequency Hz (0 = silence), duration s]. */
export const SOUND_SAMPLE_RATE = 22050;
export const SOUND_AMPLITUDE = 0.55;
export const SOUND_FADE_SEC = 0.012;

export const SOUND_TONES = {
  'rest-done': [[880, 0.16], [0, 0.07], [1175, 0.26]],
  'rest-warning': [[988, 0.1], [0, 0.09], [988, 0.1]],
  tick: [[1500, 0.06]],
} as const satisfies Record<string, readonly (readonly [number, number])[]>;
