/**
 * Downloads exercise images from free-exercise-db and generates
 * src/features/exercises/data/exercises.generated.ts with local require() paths.
 *
 * Run: npm run fetch:exercises
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CATALOG } from '../src/features/exercises/data/catalog.data.ts';

const DB_JSON_URL = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json';
const DB_IMAGE_PREFIX = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/';
const IMAGES_PER_EXERCISE = 2;

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const assetsDir = join(root, 'assets', 'exercises');
const outFile = join(root, 'src', 'features', 'exercises', 'data', 'exercises.generated.ts');

interface DbExercise {
  id: string;
  name: string;
  images: string[];
}

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');
const tokens = (s: string) => s.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);
const slugify = (id: string) => id.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

function fuzzyScore(a: string, b: string): number {
  const ta = new Set(tokens(a));
  const tb = new Set(tokens(b));
  const common = [...ta].filter((t) => tb.has(t) || tb.has(`${t}s`) || tb.has(t.replace(/s$/, ''))).length;
  return common / Math.max(ta.size, tb.size);
}

function match(entry: (typeof CATALOG)[number], db: DbExercise[]): { hit?: DbExercise; how: string } {
  if (entry.sourceId) {
    const hit = db.find((e) => e.id === entry.sourceId);
    if (hit) return { hit, how: 'override' };
  }
  const exact = db.find((e) => normalize(e.name) === normalize(entry.nameEn));
  if (exact) return { hit: exact, how: 'exact' };
  const ranked = db
    .map((e) => ({ e, score: fuzzyScore(entry.nameEn, e.name) }))
    .sort((x, y) => y.score - x.score);
  if (ranked[0] && ranked[0].score >= 0.6) return { hit: ranked[0].e, how: `fuzzy ${ranked[0].score.toFixed(2)}` };
  return { how: 'none' };
}

async function download(url: string, target: string) {
  if (existsSync(target)) return;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  writeFileSync(target, Buffer.from(await res.arrayBuffer()));
}

async function main() {
  const db = (await (await fetch(DB_JSON_URL)).json()) as DbExercise[];
  console.log(`free-exercise-db: ${db.length} exercises`);
  const lines: string[] = [];
  const missing: string[] = [];

  for (const entry of CATALOG) {
    const { hit, how } = match(entry, db);
    if (!hit) {
      missing.push(entry.nameEn);
      console.warn(`✗ ${entry.nameEn.padEnd(34)} no match`);
      continue;
    }
    const slug = slugify(entry.id);
    const dir = join(assetsDir, slug);
    mkdirSync(dir, { recursive: true });
    const requires: string[] = [];
    for (const [i, img] of hit.images.slice(0, IMAGES_PER_EXERCISE).entries()) {
      const target = join(dir, `${i}.jpg`);
      await download(DB_IMAGE_PREFIX + img, target);
      requires.push(`require('${relative(dirname(outFile), target).split('\\').join('/')}')`);
    }
    lines.push(`  ${entry.id}: [${requires.join(', ')}],`);
    console.log(`✓ ${entry.nameEn.padEnd(34)} → ${hit.id} (${how})`);
  }

  const content = `/* eslint-disable */
// AUTO-GENERATED by scripts/fetch-exercises.ts — do not edit by hand.
import type { ImageSourcePropType } from 'react-native';

export const EXERCISE_IMAGES: Record<string, ImageSourcePropType[]> = {
${lines.join('\n')}
};
`;
  writeFileSync(outFile, content);
  console.log(`\nGenerated ${relative(root, outFile)}${missing.length ? ` — missing: ${missing.join(', ')}` : ''}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
