/**
 * Icons pipeline:
 *  1. downloads Tabler SVGs for icons missing in assets/icons/ (existing files are never overwritten),
 *  2. generates src/components/ui/Icon/icons.generated.ts,
 *  3. writes docs/ICONS.md (the list of icons, where they are used and their colors).
 *
 * Run: npm run icons
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { colors } from '../src/constants/colors.ts';
import { ICONS, TABLER_VERSION } from '../src/constants/icons.ts';
import { normalizeSvg } from '../src/helpers/icons/normalizeSvg.ts';

type IconKey = keyof typeof ICONS;

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const iconsDir = join(root, 'assets', 'icons');
const registryFile = join(root, 'src', 'components', 'ui', 'Icon', 'icons.generated.ts');
const docsFile = join(root, 'docs', 'ICONS.md');
const names = Object.keys(ICONS) as IconKey[];

const tablerSvgUrl = (icon: string) => `https://cdn.jsdelivr.net/npm/@tabler/icons@${TABLER_VERSION}/icons/outline/${icon}.svg`;
const tablerPage = (icon: string) => `https://tabler.io/icons/icon/${icon}`;
const fileOf = (name: IconKey) => join(iconsDir, `${name}.svg`);

async function downloadMissing() {
  mkdirSync(iconsDir, { recursive: true });
  for (const name of names) {
    if (existsSync(fileOf(name))) continue;
    const response = await fetch(tablerSvgUrl(ICONS[name].tabler));
    if (!response.ok) {
      console.warn(`✗ ${name}: tabler/${ICONS[name].tabler} → HTTP ${response.status}`);
      continue;
    }
    writeFileSync(fileOf(name), await response.text());
    console.log(`↓ ${name} ← tabler/${ICONS[name].tabler}`);
  }
}

function writeRegistry() {
  const present = names.filter((name) => existsSync(fileOf(name)));
  const entries = present.map((name) => `  '${name}': ${JSON.stringify(normalizeSvg(readFileSync(fileOf(name), 'utf8')))},`);
  const content = `/* eslint-disable */
// AUTO-GENERATED by scripts/icons.ts — do not edit by hand. Replace files in assets/icons/ and run \`npm run icons\`.
import type { IconName } from '@/constants/icons';

export const ICON_XML: Partial<Record<IconName, string>> = {
${entries.join('\n')}
};
`;
  writeFileSync(registryFile, content);
  const unknown = readdirSync(iconsDir).filter((file) => file.endsWith('.svg') && !names.includes(file.replace(/\.svg$/, '') as IconKey));
  if (unknown.length > 0) console.warn(`! Files in assets/icons/ that the app does not use: ${unknown.join(', ')}`);
  const missing = names.filter((name) => !present.includes(name));
  if (missing.length > 0) console.warn(`! Missing icons: ${missing.join(', ')}`);
  console.log(`Registry: ${present.length}/${names.length} icons`);
}

function writeDocs() {
  mkdirSync(dirname(docsFile), { recursive: true });
  const rows = names.map((name) => {
    const spec = ICONS[name];
    const hex = colors[spec.color as keyof typeof colors];
    return `| \`${name}.svg\` | [${spec.tabler}](${tablerPage(spec.tabler)}) | ${spec.usage} | ${spec.color} \`${hex}\` |`;
  });
  const content = `# Ikonice — Helix

Aplikacija koristi **${names.length}** ikonica. Početni set je [Tabler Icons](https://tabler.io/icons) ${TABLER_VERSION}
(MIT licenca, stil **outline**, 24×24, debljina linije 2).

## Kako da zameniš ikonicu

1. Preuzmi **SVG** (outline, 24×24) sa tabler.io ili bilo kog drugog seta.
2. Boja pri preuzimanju nije bitna: najbolje **crna \`#000000\`** ili \`currentColor\`.
   Aplikacija sama boji ikonicu bojom iz kolone „Boja u aplikaciji“.
3. Sačuvaj fajl u \`assets/icons/\` pod imenom iz kolone „Fajl“ (prepiši postojeći).
4. Pokreni \`npm run icons\` — novi fajlovi se registruju, postojeći se nikad ne prepisuju iz Tablera.

Veličine u aplikaciji: tab bar 24, dugmad i liste 20–22, dijalozi 28.

## Spisak

| Fajl | Tabler ikonica | Gde se koristi | Boja u aplikaciji |
|---|---|---|---|
${rows.join('\n')}
`;
  writeFileSync(docsFile, content);
  console.log(`Docs: ${docsFile.replace(`${root}/`, '')}`);
}

async function main() {
  await downloadMissing();
  writeRegistry();
  writeDocs();
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
